---
- name: Bootstrap python 3
  hosts: vps
  become: true
  tags:
    - bootstrap
    - python 

  roles:
      - mrlesmithjr.ansible_bootstrap_python

  post_tasks:
    - name: Ensure a locale exists
      locale_gen:
        name: en_US.UTF-8
        state: present


- name: Ensure sudo user mikkel is present
  hosts: vps
  become: true

  vars_files:
    - vars/credentials.yml

  tasks:
    - name: Set become group (Ubuntu)
      set_fact: become_group="sudo"
      when: ansible_os_family | lower == "debian"

    - name: Set become group (Redhat)
      set_fact: become_group="wheel"
      when: ansible_os_family | lower == "redhat"

    - name: Ensure user is present and part of sudoers
      user:
        name: mikkel
        shell: /bin/bash
        groups: '{{ become_group }}'
        append: yes
        password: '{{ user_mikkel_pass }}'
        generate_ssh_key: yes
        ssh_key_bits: 4096


- name: Harden SSH
  hosts: vps
  become: true
  tags:
    - ssh

  vars:
    sshd_log_level: 'INFO'

    
  pre_tasks:
    - name: Set authorized ssh keys
      authorized_key:
        user: mikkel
        state: present
        key: https://github.com/Duckle29.keys

  roles:
    - dev-sec.ssh-hardening


- name: Install acme.sh, aquire certs, and generate dhparams
  hosts: vps
  become: true
  tags:
    - ssl

  vars_files:
    - vars/credentials.yml
    - vars/shared_vars.yml

  vars:
    acme_sh_copy_certs_to_path: '{{ cert_dir }}'
    acme_sh_become_user: "root"

    acme_sh_default_staging: false
    acme_sh_default_force_issue: false
    acme_sh_default_dns_provider: "dns_cf"
    acme_sh_default_dns_sleep: 120
    acme_sh_default_extra_flags_issue: '-k 4096'
    acme_sh_default_install_cert_reloadcmd: "sudo systemctl reload nginx"

    acme_sh_domains:
      - domains: ["mikkel.cc", "*.mikkel.cc"]
        debug: False 
    
    dhparams_remote_directory: '{{ cert_dir }}'
    dhparams_key_size: 4096

  roles:
    - { role: "nickjj.acme_sh", tags: ["acme_sh"] }
    - duckle29.dhparam

- name: Ensure the required python-docker bindings are installed
  hosts: vps
  become: true
  tags:
    - docker
    - python
  
  tasks:
    - name: Install docker api and docker-compose api
      pip:
        name:
          - docker
          - docker-compose

- name: Install the latest version of Docker-CE
  hosts: vps
  become: true
  tags:
    - docker
  
  vars:
    docker_edition: 'ce'
    docker_package_state: latest

    docker_service_state: started
    docker_service_enabled: true

    docker_install_compose: true
    
    docker_users:
      - mikkel
  
  roles:
    - geerlingguy.docker

- name: Install nginx
  hosts: vps
  become: true
  tags:
    - nginx

  vars_files:
    - vars/shared_vars.yml
    - vars/nextcloud/php.yml
    - vars/nextcloud/main.yml

  pre_tasks:
    - name: Remove apache
      apt: 
        name: apache2
        state: absent

  roles:
    - nginxinc.nginx

  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded

  post_tasks:    
    - name: Make snippet directory
      file:
        dest: /etc/nginx/snippets
        state: directory
      notify:
        - reload nginx

    - name: Copy ssl snippet
      template:
        src: templates/nginx/ssl_snippets.j2
        dest: /etc/nginx/snippets/ssl
      notify:
        - reload nginx
    
    - name: Remove default nginx site
      file:
        dest: /etc/nginx/conf.d/default.conf
        state: absent
      notify:
        - reload nginx
    
    # Deploys all .conf.j2 files in templates/nginx/sites
    - name: Deploy site configs
      template:
        src: '{{ item }}'
        dest: '/etc/nginx/conf.d/{{ (item | basename | splitext)[0] }}'
      with_fileglob:
        - templates/nginx/sites/*.conf.j2
      notify:
        - reload nginx

- name: Deploy resume website
  hosts: vps
  become: true
  tags:
    - resume_site
  
  vars_files:
    - vars/shared_vars.yml
    - vars/credentials.yml

  tasks:
    - name: Clone site via git
      git:
        repo: 'https://github.com/Duckle29/startbootstrap-resume.git'
        dest: '{{ mikkelcc_webroot }}'

    - name: Install webhook server
      include_role: 
        name: webhook_server
    
    - name: Change ownership of resume site files
      file:
        group: gunicorn
        owner: gunicorn
        recurse: true
        path: '{{ mikkelcc_webroot }}'
        state: directory

- name: Install thelounge
  hosts: vps
  become: true
  tags:
    - thelounge
  
  tasks:
    - name: Install nodejs
      include_role:
        name: geerlingguy.nodejs
      vars:
        nodejs_version: "12.x"
        nodejs_install_npm_user: root

    - name: Get the latest release info
      uri:
        method: GET
        url: https://api.github.com/repos/thelounge/thelounge/releases/latest
        return_content: true
      register: lounge_json_response
    
    - name: Latest version is
      debug:
        msg: "{{ lounge_json_response.json.assets.0.browser_download_url | regex_replace('^.*thelounge_((\\d\\.*)+)_all\\.deb', '\\1') }}"
      failed_when: lounge_json_response.json.assets.0.browser_download_url is not regex("thelounge_((\d\.*)+)_all\.deb")

    - name: Get the latest thelounge .deb
      get_url: 
        url: '{{ lounge_json_response.json.assets.0.browser_download_url }}'
        dest: /root/
      register: lounge_deb_file
    
    - name: Install thelounge
      apt:
        deb: '{{ lounge_deb_file.dest }}'

    - name: Remove .deb file
      file:
        state: absent
        path: '{{ lounge_deb_file.dest }}'

    - name: Stop thelounge before changing config
      service:
        name: thelounge
        state: stopped

    - name: Set up config
      template:
        src: templates/thelounge-config.js.j2
        dest: /etc/thelounge/config.js

    - name: Start and enable thelounge
      service:
        enabled: yes
        name: thelounge
        state: started

- name: Install unifi SDN
  hosts: vps
  become: true
  tags:
    - unifi

  tasks:
    - name: Add an apt key for mongoDB
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 0C49F3730359A14518585931BC711F9BA15703C6

    - name: Add an apt key for unifi
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 06E85760C0A52C50 

    - name: Add mongoDB repository
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse
        state: present
        filename: mongodb-org-3.4

    - name: Add unifi repository
      apt_repository:
        repo: deb http://www.ubnt.com/downloads/unifi/debian stable ubiquiti
        state: present
        filename: 100-ubnt-unifi

    - name: Install unifi SDN
      apt:
        name: unifi
        state: present

- name: Install PartKeepr
  hosts: vps
  become: true
  tags:
    - partkeepr    

  vars_files:
    - vars/credentials.yml
  
  vars:
    pk_db_name: partkeepr
    pk_db_user: partkeepr
    pk_db_host: partkeepr-mariadb

    pk_cron: '0 0,6,12,18 * * *  /usr/bin/php /var/www/html/app/console partkeepr:cron:run'
  
  tasks:
    - name: Ensure the partkeepr docker network exists
      docker_network:
        name: partkeepr
        ipam_config:
          - subnet: 10.100.100.0/28
            gateway: 10.100.100.2
            iprange: 10.100.100.0/28
        internal: no
    
    - name: Create a volume for persisiting the database
      docker_volume:
        name: pk_mariadb
    
    - name: Create a volume for persisting the partkeeper data
      docker_volume:
        name: pk_data

    - name: Ensure MariaDB container is running
      docker_container:
        name: '{{ pk_db_host }}'
        image: mariadb:10.1
        state: started
        pull: true
        mounts:
          - source: pk_mariadb
            target: /var/lib/mysql
        env:
          MYSQL_RANDOM_ROOT_PASSWORD: "yes"
          MYSQL_DATABASE: '{{ pk_db_name | string }}'
          MYSQL_USER: '{{ pk_db_user | string }}'
          MYSQL_PASSWORD: "{{ pk_db_pass | string }}"

        networks_cli_compatible: yes
        networks:
          - name: partkeepr

    - name: Ensure PartKeepr container is running
      docker_container:
        name: partkeepr
        image: "mhubig/partkeepr"
        state: started
        pull: true
        mounts:
          - source: pk_data
            target: /var/www/html/data
        env:
          PARTKEEPR_OCTOPART_APIKEY: '{{ pk_octopart_token | string}}'
          PARTKEEPR_DATABASE_HOST: '{{ pk_db_host | string }}'
          PARTKEEPR_DATABASE_USER: '{{ pk_db_user | string }}'
          PARTKEEPR_DATABASE_NAME: '{{ pk_db_name | string }}'
          PARTKEEPR_DATABASE_PASS: '{{ pk_db_pass | string }}'
          PARTKEEPR_DATABASE_PORT: '3306'


        networks_cli_compatible: yes
        networks:
          - name: partkeepr
        ports:
          - "127.0.0.1:8085:80/tcp"

    - name: Inject partkeepr cronjob into its container
      shell: "docker exec partkeepr bash -lc \"( crontab -l | echo {{pk_cron | quote }}) | sort - | uniq - | crontab - \""
      changed_when: False


- name: Install UNMS
  hosts: vps
  become: true
  tags:
    - unms

  tasks:
    - name: Install dependencies
      apt:
        name: ['curl', 'netcat', 'sudo', 'bash']
        state: present

    - name: Check that UNMS isn't already installed
      stat:
        path: /home/unms/app/unms-cli
      register: unms_stat
  
    - name: Install UNMS
      shell: "curl -fsSL https://unms.com/install > /tmp/unms_inst.sh && sudo bash /tmp/unms_inst.sh --public-https-port 443 --http-port 8081 --https-port 9443 --unattended"
      when: not unms_stat.stat.exists

- name: Install sopel
  hosts: vps
  become: true
  tags:
    - sopel

  vars_files:
    - vars/credentials.yml

  vars:
    sopel_command_prefix: '\$'
    
    sopel_instance_name: dumDuck
    sopel_nick: DumDuckBot
    sopel_auth_user: '{{ sopel_irc_user }}'
    sopel_auth_pass: '{{ sopel_irc_pass }}'
    sopel_install_dir: '/srv/sopel'

    sopel_channels: 
      - '##botspam'
      - '#reprap'
      - '#bigdelta'
      - '#partkeepr'

    sopel_bot_owner: 'Duckle29'

    sopel_enabled_plugins:
      - help
      - admin
      - clock
      - find_updates
      - reload
      - currency
      - remind
      - search
      - version
      - xkcd
      - wolfram
      - calc
      - funreplies

    sopel_ignored_nicks:
      - kthx
      - mcrib
      - ghtx
    
    sopel_config_extra: |
      [wolfram]
      app_id = {{ wolfram_alpha_key }}
      max_public = 3
      units = metric

      [currency]
      fixer_io_key = {{ fixer_io_key }}
      auto_convert = true
  
  handlers:
    - name: restart sopel
      become: true
      service:
        name: 'sopel-{{ sopel_instance_name }}'
        state: restarted
  
  roles:
    - sopel.sopel
  
  post_tasks:
    - name: Install wolfram plugin
      pip:
        name: sopel-modules.wolfram
        state: present
        virtualenv: '{{ sopel_install_dir }}/venv_{{ sopel_instance_name }}'
        virtualenv_command: '/usr/bin/python3 -m venv'
      notify: restart sopel

- name: Set up autotorrent
  hosts: vps
  become: true
  tags:
    - autotorrent
    - deluge

  vars_files:
    - vars/credentials.yml
    - vars/shared_vars.yml

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes

  tasks:
    - name: Add deluge ppa
      apt_repository:
        repo: ppa:deluge-team/stable

    - name: Install deluged
      apt:
        name:
          - deluged
          - deluge-console
        state: present
    
    - name: Add deluge system user
      user:
        name: deluge
        password: '!'
        home: /srv/deluge
        system: yes
        state: present
    
    - name: Add deluged systemd service
      template:
        src: templates/deluge/unitfile.service.j2
        dest: /etc/systemd/system/deluged.service
      when: ansible_service_mgr == 'systemd'
      notify:
        - reload systemd

    - name: Add deluge admin user
      lineinfile:
        line: '{{ deluge_user }}:{{ deluge_pass }}:10'
        path: /srv/deluge/.config/deluge/auth
        create: true

    - name: Ensure file ownership
      file:
        path: /srv/deluge
        recurse: yes
        owner: deluge
        group: deluge

    - name: Start and enable deluged
      service:
        name: deluged
        state: started
        enabled: yes
    
    - name: Allow remote connections
      shell: 'deluge-console "config -s allow_remote True"'

    - pause:
        seconds: 5
        prompt: "Wait for deluged to start"

    - name: Allow remote connections
      shell: deluge-console "config -s allow_remote True"
      become_user: deluge
      register: ret
      failed_when: "'successfully updated' not in ret.stdout"

    - name: Install feedgen
      pip:
        name: feedgen
        executable: pip3
    
    - name: Install pytz
      pip:
        name: pytz
        executable: pip3

    - name: Create web root
      file:
        path: '{{ autotorrent_webroot }}'
        state: directory
        owner: deluge
        group: deluge
    
    - name: Install git
      apt:
        name: git
        state: present

    - name: Get torrentGen
      git:
        repo: https://github.com/Duckle29/torrentGen.git
        dest: /srv/deluge/torrentGen
        update: no
    
    - name: Ensure autoadd folder is present
      file:
        path: '/srv/deluge/torrentGen/autoadd'
        state: directory
        owner: deluge
        group: deluge

    - name: Set correct webroot in torrent gen script
      lineinfile:
        line: "webroot          = '{{ autotorrent_webroot }}/octopi/'"
        regexp: '^webroot +=.+$'
        path: /srv/deluge/torrentGen/octopi/check.py

    - name: Set up cronjob
      cron:
        name: 'autotorrent: Check for new version'
        user: 'deluge'
        minute: '0'
        hour: '*/1'
        job: /usr/bin/python3 /srv/deluge/torrentGen/octopi/check.py

- name: Install nextcloud
  hosts: vps
  become: true
  tags:
    - nextcloud

  vars_files:
    - vars/credentials.yml
    - vars/shared_vars.yml
    - vars/nextcloud/mysql.yml
    - vars/nextcloud/php.yml
    - vars/nextcloud/main.yml

  handlers:
    - name: restart php-fpm
      service:
        name: php{{ php_default_version_debian }}-fpm
        state: restarted

  pre_tasks:
  - setup:
    become: no

  tasks:
    - include_role:
        name: geerlingguy.php

    - name: Change owner of php-fpm socket
      lineinfile:
        dest: "/etc/php/{{ php_default_version_debian }}/fpm/pool.d/www.conf"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - regexp: '^listen\.owner.?=.+$'
          line: "listen.owner = {{ php_fpm_pool_user }}"
        - regexp: '^listen\.group.?=.+$'
          line: "listen.group = {{ php_fpm_pool_group }}"
      when: php_enable_php_fpm
      notify:
        - restart php-fpm

    - include_role:
        name: geerlingguy.mysql
    - include_role:
        name: aalaesar.install_nextcloud

- name: Set up firewall
  hosts: vps
  become: true
  tags:
    - firewall
  
  roles:
    - ufw

- name: Configure unattended upgrades
  hosts: vps
  become: true
  tags:
    - unattended_upgrades
  
  roles:
    - role: jnv.unattended-upgrades
      unattended_mail: 'mikkel@mikkel.cc'
