---
- name: Ensure ufw is installed
  package:
    name: ufw
    state: present

- name: Copy ufw application templates
  template:
    src: '{{ item }}'
    dest: '/etc/ufw/applications.d/{{ item[:-3] | basename }}'
  with_fileglob:
    - templates/*.j2

- name: Reload ufw
  community.general.ufw:
    state: reloaded

- name: Allow apps
  community.general.ufw:
    app: '{{ item }}'
    rule: allow
  loop: '{{ ufw_allowed_apps }}'

- name: Set up default outgoing policy
  community.general.ufw:
    default: '{{ ufw_default_outgoing }}'
    direction: outgoing

- name: Set up default incoming policy and enable UFW
  community.general.ufw:
    state: enabled
    default: '{{ ufw_default_incoming }}'
    direction: incoming